[2025-02-20T03:45:29.463+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T03:45:29.463+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T03:45:29.543+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [queued]>
[2025-02-20T03:45:29.590+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [queued]>
[2025-02-20T03:45:29.592+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-02-20T03:45:29.674+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): extract_task> on 2025-02-20 03:24:34.161456+00:00
[2025-02-20T03:45:29.699+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-02-20T03:45:29.701+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-02-20T03:45:29.731+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2025-02-20T03:45:29.688+0000] {standard_task_runner.py:72} INFO - Started process 526 to run task
[2025-02-20T03:45:29.762+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'extract_task', 'manual__2025-02-20T03:24:34.161456+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmpbprc2h4k']
[2025-02-20T03:45:29.796+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask extract_task
[2025-02-20T03:45:29.847+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T03:45:29.902+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [running]> on host ***-airflow-scheduler
[2025-02-20T03:45:30.366+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T03:24:34.161456+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T03:24:34.161456+00:00'
[2025-02-20T03:45:30.377+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T03:45:30.554+0000] {base.py:84} INFO - Retrieving connection 'spark_main'
[2025-02-20T03:45:30.559+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py
[2025-02-20T03:45:37.619+0000] {spark_submit.py:641} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-20T03:45:37.849+0000] {spark_submit.py:641} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-02-20T03:45:37.852+0000] {spark_submit.py:641} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-02-20T03:45:37.859+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql added as a dependency
[2025-02-20T03:45:37.861+0000] {spark_submit.py:641} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-7cbb2d45-b679-4c89-af89-067254040f14;1.0
[2025-02-20T03:45:37.863+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T03:45:38.138+0000] {spark_submit.py:641} INFO - found org.postgresql#postgresql;42.2.18 in central
[2025-02-20T03:45:38.183+0000] {spark_submit.py:641} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-20T03:45:38.238+0000] {spark_submit.py:641} INFO - :: resolution report :: resolve 354ms :: artifacts dl 23ms
[2025-02-20T03:45:38.240+0000] {spark_submit.py:641} INFO - :: modules in use:
[2025-02-20T03:45:38.241+0000] {spark_submit.py:641} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-20T03:45:38.243+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2025-02-20T03:45:38.244+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:45:38.245+0000] {spark_submit.py:641} INFO - |                  |            modules            ||   artifacts   |
[2025-02-20T03:45:38.247+0000] {spark_submit.py:641} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-20T03:45:38.249+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:45:38.251+0000] {spark_submit.py:641} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-02-20T03:45:38.252+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:45:38.254+0000] {spark_submit.py:641} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-7cbb2d45-b679-4c89-af89-067254040f14
[2025-02-20T03:45:38.255+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T03:45:38.258+0000] {spark_submit.py:641} INFO - 0 artifacts copied, 2 already retrieved (0kB/11ms)
[2025-02-20T03:45:39.132+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-20T03:45:43.549+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO SparkContext: Running Spark version 3.3.2
[2025-02-20T03:45:43.717+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO ResourceUtils: ==============================================================
[2025-02-20T03:45:43.719+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-20T03:45:43.721+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO ResourceUtils: ==============================================================
[2025-02-20T03:45:43.723+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO SparkContext: Submitted application: ***_extract
[2025-02-20T03:45:43.827+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-20T03:45:43.884+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO ResourceProfile: Limiting resource is cpu
[2025-02-20T03:45:43.887+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:43 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-20T03:45:44.634+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:44 INFO SecurityManager: Changing view acls to: airflow
[2025-02-20T03:45:44.640+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:44 INFO SecurityManager: Changing modify acls to: airflow
[2025-02-20T03:45:44.643+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:44 INFO SecurityManager: Changing view acls groups to:
[2025-02-20T03:45:44.644+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:44 INFO SecurityManager: Changing modify acls groups to:
[2025-02-20T03:45:44.646+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:44 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-02-20T03:45:45.267+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO Utils: Successfully started service 'sparkDriver' on port 35419.
[2025-02-20T03:45:45.375+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO SparkEnv: Registering MapOutputTracker
[2025-02-20T03:45:45.514+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-20T03:45:45.632+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-20T03:45:45.634+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-20T03:45:45.646+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-20T03:45:45.702+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e8f8d76a-e91c-4deb-918d-55dc62ff856c
[2025-02-20T03:45:45.744+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-20T03:45:45.796+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:45 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-20T03:45:46.419+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-02-20T03:45:46.485+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 ERROR SparkContext: Failed to add /opt/postgresql-42.2.18.jar to Spark environment
[2025-02-20T03:45:46.487+0000] {spark_submit.py:641} INFO - java.io.FileNotFoundException: Jar /opt/postgresql-42.2.18.jar not found
[2025-02-20T03:45:46.488+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1959)
[2025-02-20T03:45:46.489+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.addJar(SparkContext.scala:2014)
[2025-02-20T03:45:46.490+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-02-20T03:45:46.491+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-02-20T03:45:46.492+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-02-20T03:45:46.493+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-02-20T03:45:46.494+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-02-20T03:45:46.495+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-02-20T03:45:46.496+0000] {spark_submit.py:641} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-02-20T03:45:46.497+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-02-20T03:45:46.498+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-02-20T03:45:46.499+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-02-20T03:45:46.500+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-02-20T03:45:46.500+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-02-20T03:45:46.501+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-02-20T03:45:46.502+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-02-20T03:45:46.503+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-02-20T03:45:46.504+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-02-20T03:45:46.505+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-02-20T03:45:46.505+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-20T03:45:46.506+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-20T03:45:46.507+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-20T03:45:46.508+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar at file:///home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar with timestamp 1740023143530
[2025-02-20T03:45:46.508+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Utils: Copying /home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar to /tmp/spark-6f57980b-e605-4382-86f6-1318aa855886/userFiles-afd280ba-2290-4eb2-8f93-bf3f78429499/org.postgresql_postgresql-42.2.18.jar
[2025-02-20T03:45:46.523+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar at file:///home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar with timestamp 1740023143530
[2025-02-20T03:45:46.524+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Utils: Copying /home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar to /tmp/spark-6f57980b-e605-4382-86f6-1318aa855886/userFiles-afd280ba-2290-4eb2-8f93-bf3f78429499/org.checkerframework_checker-qual-3.5.0.jar
[2025-02-20T03:45:46.656+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Executor: Starting executor ID driver on host ***-airflow-scheduler
[2025-02-20T03:45:46.664+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-02-20T03:45:46.677+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Executor: Fetching file:///home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar with timestamp 1740023143530
[2025-02-20T03:45:46.702+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Utils: /home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar has been previously copied to /tmp/spark-6f57980b-e605-4382-86f6-1318aa855886/userFiles-afd280ba-2290-4eb2-8f93-bf3f78429499/org.postgresql_postgresql-42.2.18.jar
[2025-02-20T03:45:46.707+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Executor: Fetching file:///home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar with timestamp 1740023143530
[2025-02-20T03:45:46.709+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Utils: /home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar has been previously copied to /tmp/spark-6f57980b-e605-4382-86f6-1318aa855886/userFiles-afd280ba-2290-4eb2-8f93-bf3f78429499/org.checkerframework_checker-qual-3.5.0.jar
[2025-02-20T03:45:46.728+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42131.
[2025-02-20T03:45:46.730+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO NettyBlockTransferService: Server created on ***-airflow-scheduler:42131
[2025-02-20T03:45:46.732+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-02-20T03:45:46.740+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, ***-airflow-scheduler, 42131, None)
[2025-02-20T03:45:46.746+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO BlockManagerMasterEndpoint: Registering block manager ***-airflow-scheduler:42131 with 434.4 MiB RAM, BlockManagerId(driver, ***-airflow-scheduler, 42131, None)
[2025-02-20T03:45:46.749+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, ***-airflow-scheduler, 42131, None)
[2025-02-20T03:45:46.751+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:46 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, ***-airflow-scheduler, 42131, None)
[2025-02-20T03:45:48.665+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-20T03:45:48.668+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/exceptions.py", line 66, in kaggle_api_raise_for_status
[2025-02-20T03:45:48.669+0000] {spark_submit.py:641} INFO - response.raise_for_status()
[2025-02-20T03:45:48.671+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
[2025-02-20T03:45:48.672+0000] {spark_submit.py:641} INFO - raise HTTPError(http_error_msg, response=self)
[2025-02-20T03:45:48.674+0000] {spark_submit.py:641} INFO - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/datasets/view/sanjanchaudhari/employees-performance-for-hr-analytics
[2025-02-20T03:45:48.675+0000] {spark_submit.py:641} INFO - 
[2025-02-20T03:45:48.677+0000] {spark_submit.py:641} INFO - The above exception was the direct cause of the following exception:
[2025-02-20T03:45:48.678+0000] {spark_submit.py:641} INFO - 
[2025-02-20T03:45:48.679+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-20T03:45:48.681+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 43, in <module>
[2025-02-20T03:45:48.682+0000] {spark_submit.py:641} INFO - extract()
[2025-02-20T03:45:48.684+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 24, in extract
[2025-02-20T03:45:48.685+0000] {spark_submit.py:641} INFO - dataset_path = kagglehub.dataset_download("sanjanchaudhari/employees-performance-for-hr-analytics")
[2025-02-20T03:45:48.687+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/datasets.py", line 35, in dataset_download
[2025-02-20T03:45:48.689+0000] {spark_submit.py:641} INFO - path, _ = registry.dataset_resolver(h, path, force_download=force_download)
[2025-02-20T03:45:48.691+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/registry.py", line 28, in __call__
[2025-02-20T03:45:48.692+0000] {spark_submit.py:641} INFO - return impl(*args, **kwargs)
[2025-02-20T03:45:48.694+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/resolver.py", line 29, in __call__
[2025-02-20T03:45:48.696+0000] {spark_submit.py:641} INFO - path, version = self._resolve(handle, path, force_download=force_download)
[2025-02-20T03:45:48.698+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/http_resolver.py", line 107, in _resolve
[2025-02-20T03:45:48.699+0000] {spark_submit.py:641} INFO - h = h.with_version(_get_current_version(api_client, h))
[2025-02-20T03:45:48.701+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/http_resolver.py", line 290, in _get_current_version
[2025-02-20T03:45:48.703+0000] {spark_submit.py:641} INFO - json_response = api_client.get(_build_get_dataset_url_path(h), h)
[2025-02-20T03:45:48.704+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/clients.py", line 139, in get
[2025-02-20T03:45:48.706+0000] {spark_submit.py:641} INFO - kaggle_api_raise_for_status(response, resource_handle)
[2025-02-20T03:45:48.707+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/exceptions.py", line 106, in kaggle_api_raise_for_status
[2025-02-20T03:45:48.710+0000] {spark_submit.py:641} INFO - raise KaggleApiHTTPError(message, response=response) from e
[2025-02-20T03:45:48.712+0000] {spark_submit.py:641} INFO - kagglehub.exceptions.KaggleApiHTTPError: 404 Client Error.
[2025-02-20T03:45:48.714+0000] {spark_submit.py:641} INFO - 
[2025-02-20T03:45:48.716+0000] {spark_submit.py:641} INFO - Resource not found at URL: https://www.kaggle.com/datasets/sanjanchaudhari/employees-performance-for-hr-analytics
[2025-02-20T03:45:48.718+0000] {spark_submit.py:641} INFO - Please make sure you specified the correct resource identifiers.
[2025-02-20T03:45:48.761+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO SparkContext: Invoking stop() from shutdown hook
[2025-02-20T03:45:48.778+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO SparkUI: Stopped Spark web UI at http://***-airflow-scheduler:4040
[2025-02-20T03:45:48.792+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-20T03:45:48.812+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO MemoryStore: MemoryStore cleared
[2025-02-20T03:45:48.814+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO BlockManager: BlockManager stopped
[2025-02-20T03:45:48.824+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-20T03:45:48.828+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-20T03:45:48.837+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO SparkContext: Successfully stopped SparkContext
[2025-02-20T03:45:48.839+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO ShutdownHookManager: Shutdown hook called
[2025-02-20T03:45:48.841+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-6f57980b-e605-4382-86f6-1318aa855886
[2025-02-20T03:45:48.846+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-fb581062-cbb4-4d8c-b4f6-1fa68283b0e5
[2025-02-20T03:45:48.858+0000] {spark_submit.py:641} INFO - 25/02/20 03:45:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-6f57980b-e605-4382-86f6-1318aa855886/pyspark-1f8f1aa7-cf3d-4242-b84a-8b4eb0f42984
[2025-02-20T03:45:48.930+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T03:45:48.945+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=extract_task, run_id=manual__2025-02-20T03:24:34.161456+00:00, execution_date=20250220T032434, start_date=20250220T034529, end_date=20250220T034548
[2025-02-20T03:45:49.002+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T03:45:49.005+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task extract_task (Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.; 526)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T03:45:49.019+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T03:45:49.055+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T03:45:49.063+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
