[2025-02-20T03:37:05.658+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T03:37:05.692+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [queued]>
[2025-02-20T03:37:05.713+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [queued]>
[2025-02-20T03:37:05.715+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-20T03:37:05.743+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): extract_task> on 2025-02-20 03:24:34.161456+00:00
[2025-02-20T03:37:05.753+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2025-02-20T03:37:05.758+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'extract_task', 'manual__2025-02-20T03:24:34.161456+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmpvgg33awb']
[2025-02-20T03:37:05.765+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask extract_task
[2025-02-20T03:37:05.829+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T03:37:05.920+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [running]> on host ***-airflow-scheduler
[2025-02-20T03:37:06.284+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T03:24:34.161456+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T03:24:34.161456+00:00'
[2025-02-20T03:37:06.290+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T03:37:06.402+0000] {base.py:84} INFO - Retrieving connection 'spark_main'
[2025-02-20T03:37:06.405+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py
[2025-02-20T03:37:11.923+0000] {spark_submit.py:641} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-20T03:37:12.118+0000] {spark_submit.py:641} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-02-20T03:37:12.120+0000] {spark_submit.py:641} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-02-20T03:37:12.126+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql added as a dependency
[2025-02-20T03:37:12.127+0000] {spark_submit.py:641} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-89cf5cfb-5002-4cea-a78e-ecf0dc68d363;1.0
[2025-02-20T03:37:12.128+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T03:37:14.381+0000] {spark_submit.py:641} INFO - found org.postgresql#postgresql;42.2.18 in central
[2025-02-20T03:37:14.806+0000] {spark_submit.py:641} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-20T03:37:15.023+0000] {spark_submit.py:641} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.18/postgresql-42.2.18.jar ...
[2025-02-20T03:37:18.318+0000] {spark_submit.py:641} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.2.18!postgresql.jar (3482ms)
[2025-02-20T03:37:18.599+0000] {spark_submit.py:641} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-20T03:37:19.531+0000] {spark_submit.py:641} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (1183ms)
[2025-02-20T03:37:19.533+0000] {spark_submit.py:641} INFO - :: resolution report :: resolve 2699ms :: artifacts dl 4707ms
[2025-02-20T03:37:19.534+0000] {spark_submit.py:641} INFO - :: modules in use:
[2025-02-20T03:37:19.535+0000] {spark_submit.py:641} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-20T03:37:19.537+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2025-02-20T03:37:19.538+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:37:19.540+0000] {spark_submit.py:641} INFO - |                  |            modules            ||   artifacts   |
[2025-02-20T03:37:19.542+0000] {spark_submit.py:641} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-20T03:37:19.544+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:37:19.546+0000] {spark_submit.py:641} INFO - |      default     |   2   |   2   |   2   |   0   ||   2   |   2   |
[2025-02-20T03:37:19.547+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:37:19.548+0000] {spark_submit.py:641} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-89cf5cfb-5002-4cea-a78e-ecf0dc68d363
[2025-02-20T03:37:19.549+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T03:37:19.590+0000] {spark_submit.py:641} INFO - 2 artifacts copied, 0 already retrieved (1190kB/48ms)
[2025-02-20T03:37:20.357+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-20T03:37:22.993+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:22 INFO SparkContext: Running Spark version 3.3.2
[2025-02-20T03:37:23.024+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO ResourceUtils: ==============================================================
[2025-02-20T03:37:23.026+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-20T03:37:23.027+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO ResourceUtils: ==============================================================
[2025-02-20T03:37:23.029+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO SparkContext: Submitted application: ETL-Extract
[2025-02-20T03:37:23.080+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-20T03:37:23.100+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO ResourceProfile: Limiting resource is cpu
[2025-02-20T03:37:23.103+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-20T03:37:23.375+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO SecurityManager: Changing view acls to: airflow
[2025-02-20T03:37:23.377+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO SecurityManager: Changing modify acls to: airflow
[2025-02-20T03:37:23.378+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO SecurityManager: Changing view acls groups to:
[2025-02-20T03:37:23.382+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO SecurityManager: Changing modify acls groups to:
[2025-02-20T03:37:23.384+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-02-20T03:37:23.982+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:23 INFO Utils: Successfully started service 'sparkDriver' on port 37967.
[2025-02-20T03:37:24.058+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkEnv: Registering MapOutputTracker
[2025-02-20T03:37:24.125+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-20T03:37:24.192+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-20T03:37:24.194+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-20T03:37:24.202+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-20T03:37:24.257+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4ea6f407-e4c1-4b45-8dd7-df379d573e42
[2025-02-20T03:37:24.291+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-20T03:37:24.320+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-20T03:37:24.847+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-02-20T03:37:24.914+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkContext: Added JAR file:///home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar at spark://***-airflow-scheduler:37967/jars/org.postgresql_postgresql-42.2.18.jar with timestamp 1740022642983
[2025-02-20T03:37:24.916+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkContext: Added JAR file:///home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar at spark://***-airflow-scheduler:37967/jars/org.checkerframework_checker-qual-3.5.0.jar with timestamp 1740022642983
[2025-02-20T03:37:24.919+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar at spark://***-airflow-scheduler:37967/files/org.postgresql_postgresql-42.2.18.jar with timestamp 1740022642983
[2025-02-20T03:37:24.922+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO Utils: Copying /home/airflow/.ivy2/jars/org.postgresql_postgresql-42.2.18.jar to /tmp/spark-9e91ab69-c212-44d9-8d7f-a687a5f604a0/userFiles-768d5778-77d6-4b9f-8a79-5e1d3f7f94eb/org.postgresql_postgresql-42.2.18.jar
[2025-02-20T03:37:24.976+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO SparkContext: Added file file:///home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar at spark://***-airflow-scheduler:37967/files/org.checkerframework_checker-qual-3.5.0.jar with timestamp 1740022642983
[2025-02-20T03:37:24.978+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:24 INFO Utils: Copying /home/airflow/.ivy2/jars/org.checkerframework_checker-qual-3.5.0.jar to /tmp/spark-9e91ab69-c212-44d9-8d7f-a687a5f604a0/userFiles-768d5778-77d6-4b9f-8a79-5e1d3f7f94eb/org.checkerframework_checker-qual-3.5.0.jar
[2025-02-20T03:37:25.172+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:25 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://***-spark-master:7077...
[2025-02-20T03:37:25.262+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:25 INFO TransportClientFactory: Successfully created connection to ***-spark-master/172.19.0.3:7077 after 63 ms (0 ms spent in bootstraps)
[2025-02-20T03:37:27.332+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250220033727-0000
[2025-02-20T03:37:27.350+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34753.
[2025-02-20T03:37:27.352+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO NettyBlockTransferService: Server created on ***-airflow-scheduler:34753
[2025-02-20T03:37:27.355+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-02-20T03:37:27.375+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, ***-airflow-scheduler, 34753, None)
[2025-02-20T03:37:27.400+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO BlockManagerMasterEndpoint: Registering block manager ***-airflow-scheduler:34753 with 434.4 MiB RAM, BlockManagerId(driver, ***-airflow-scheduler, 34753, None)
[2025-02-20T03:37:27.407+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, ***-airflow-scheduler, 34753, None)
[2025-02-20T03:37:27.413+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, ***-airflow-scheduler, 34753, None)
[2025-02-20T03:37:27.646+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250220033727-0000/0 on worker-20250220033415-172.19.0.4-40993 (172.19.0.4:40993) with 1 core(s)
[2025-02-20T03:37:27.651+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:27 INFO StandaloneSchedulerBackend: Granted executor ID app-20250220033727-0000/0 on hostPort 172.19.0.4:40993 with 1 core(s), 1024.0 MiB RAM
[2025-02-20T03:37:28.210+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:28 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-02-20T03:37:30.949+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-20T03:37:30.954+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/exceptions.py", line 66, in kaggle_api_raise_for_status
[2025-02-20T03:37:30.959+0000] {spark_submit.py:641} INFO - response.raise_for_status()
[2025-02-20T03:37:30.964+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
[2025-02-20T03:37:30.969+0000] {spark_submit.py:641} INFO - raise HTTPError(http_error_msg, response=self)
[2025-02-20T03:37:30.980+0000] {spark_submit.py:641} INFO - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/datasets/view/sanjanchaudhari/employees-performance-for-hr-analytics
[2025-02-20T03:37:30.984+0000] {spark_submit.py:641} INFO - 
[2025-02-20T03:37:30.990+0000] {spark_submit.py:641} INFO - The above exception was the direct cause of the following exception:
[2025-02-20T03:37:30.995+0000] {spark_submit.py:641} INFO - 
[2025-02-20T03:37:31.001+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-20T03:37:31.003+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 35, in <module>
[2025-02-20T03:37:31.007+0000] {spark_submit.py:641} INFO - extract()
[2025-02-20T03:37:31.013+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 16, in extract
[2025-02-20T03:37:31.016+0000] {spark_submit.py:641} INFO - dataset_path = kagglehub.dataset_download("sanjanchaudhari/employees-performance-for-hr-analytics")
[2025-02-20T03:37:31.019+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/datasets.py", line 35, in dataset_download
[2025-02-20T03:37:31.022+0000] {spark_submit.py:641} INFO - path, _ = registry.dataset_resolver(h, path, force_download=force_download)
[2025-02-20T03:37:31.030+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/registry.py", line 28, in __call__
[2025-02-20T03:37:31.033+0000] {spark_submit.py:641} INFO - return impl(*args, **kwargs)
[2025-02-20T03:37:31.035+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/resolver.py", line 29, in __call__
[2025-02-20T03:37:31.037+0000] {spark_submit.py:641} INFO - path, version = self._resolve(handle, path, force_download=force_download)
[2025-02-20T03:37:31.038+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/http_resolver.py", line 107, in _resolve
[2025-02-20T03:37:31.040+0000] {spark_submit.py:641} INFO - h = h.with_version(_get_current_version(api_client, h))
[2025-02-20T03:37:31.043+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/http_resolver.py", line 290, in _get_current_version
[2025-02-20T03:37:31.045+0000] {spark_submit.py:641} INFO - json_response = api_client.get(_build_get_dataset_url_path(h), h)
[2025-02-20T03:37:31.047+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/clients.py", line 139, in get
[2025-02-20T03:37:31.048+0000] {spark_submit.py:641} INFO - kaggle_api_raise_for_status(response, resource_handle)
[2025-02-20T03:37:31.050+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.9/site-packages/kagglehub/exceptions.py", line 106, in kaggle_api_raise_for_status
[2025-02-20T03:37:31.051+0000] {spark_submit.py:641} INFO - raise KaggleApiHTTPError(message, response=response) from e
[2025-02-20T03:37:31.053+0000] {spark_submit.py:641} INFO - kagglehub.exceptions.KaggleApiHTTPError: 404 Client Error.
[2025-02-20T03:37:31.055+0000] {spark_submit.py:641} INFO - 
[2025-02-20T03:37:31.057+0000] {spark_submit.py:641} INFO - Resource not found at URL: https://www.kaggle.com/datasets/sanjanchaudhari/employees-performance-for-hr-analytics
[2025-02-20T03:37:31.061+0000] {spark_submit.py:641} INFO - Please make sure you specified the correct resource identifiers.
[2025-02-20T03:37:31.167+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO SparkContext: Invoking stop() from shutdown hook
[2025-02-20T03:37:31.187+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO SparkUI: Stopped Spark web UI at http://***-airflow-scheduler:4040
[2025-02-20T03:37:31.193+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-02-20T03:37:31.203+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-02-20T03:37:31.230+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-20T03:37:31.272+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO MemoryStore: MemoryStore cleared
[2025-02-20T03:37:31.275+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO BlockManager: BlockManager stopped
[2025-02-20T03:37:31.287+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-20T03:37:31.292+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-20T03:37:31.321+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO SparkContext: Successfully stopped SparkContext
[2025-02-20T03:37:31.323+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO ShutdownHookManager: Shutdown hook called
[2025-02-20T03:37:31.325+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO ShutdownHookManager: Deleting directory /tmp/spark-9e91ab69-c212-44d9-8d7f-a687a5f604a0
[2025-02-20T03:37:31.330+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO ShutdownHookManager: Deleting directory /tmp/spark-56892513-75ae-453c-974d-90f605304f52
[2025-02-20T03:37:31.342+0000] {spark_submit.py:641} INFO - 25/02/20 03:37:31 INFO ShutdownHookManager: Deleting directory /tmp/spark-9e91ab69-c212-44d9-8d7f-a687a5f604a0/pyspark-3effe5c1-4e5d-4b06-9ce0-616ae4b58049
[2025-02-20T03:37:31.603+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T03:37:31.648+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=extract_task, run_id=manual__2025-02-20T03:24:34.161456+00:00, execution_date=20250220T032434, start_date=20250220T033705, end_date=20250220T033731
[2025-02-20T03:37:31.759+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T03:37:31.766+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 53 for task extract_task (Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.; 198)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T03:37:31.821+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T03:37:31.894+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T03:37:31.901+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
